# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release'
        required: true
        default: 'Release'
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'


permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build executable with PyInstaller
      run: |
          pyinstaller --onefile rssPush.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/rssPush
          asset_name: rssPush
          asset_content_type: application/octet-stream
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
